import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const Header = () => {
    return (
      <footer>
        <Link
          href="/"
        >
          Duan Blog
        </Link>
      </footer>
    )
  }
  const Footer = () => {
    return (
      <footer>
        Footer
      </footer>
    )
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />

      </body >
    </html >
  )
}
